BEGIN;

CREATE SCHEMA IF NOT EXISTS meta;
CREATE SCHEMA IF NOT EXISTS ref;
CREATE SCHEMA IF NOT EXISTS raw_retrosheet;
CREATE SCHEMA IF NOT EXISTS raw_chadwick;
CREATE SCHEMA IF NOT EXISTS raw_lahman;
CREATE SCHEMA IF NOT EXISTS raw_statcast;
CREATE SCHEMA IF NOT EXISTS raw_mlbapi;
CREATE SCHEMA IF NOT EXISTS raw_fangraphs;
CREATE SCHEMA IF NOT EXISTS raw_bref;
CREATE SCHEMA IF NOT EXISTS raw_espn;
CREATE SCHEMA IF NOT EXISTS raw_odds;
CREATE SCHEMA IF NOT EXISTS stg;
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS mart;
CREATE SCHEMA IF NOT EXISTS util;

COMMIT;