name: Issue triage

on:
  issues:
    types: [opened, reopened]

jobs:
  label_issues:
    runs-on: self-hosted
    permissions:
      issues: write

    steps:
      - name: Add triage label
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage